#' Create a Heatmap for Association Rules
#'
#' The `rule_heatmap` function generates a heatmap visualization of association rules, 
#' showing relationships between antecedents and consequents based on a specified metric.
#'
#' @param rules An object of class `rules`, typically generated by the `apriori` function from the `arules` package.
#' @param metric A character string specifying the metric to use for coloring the heatmap. 
#'   Must be one of `"confidence"`, `"support"`, or `"lift"`. Defaults to `"confidence"`.
#' @param graph_title A character string specifying the title of the graph. 
#'   Defaults to an empty string (`""`).
#' @param low_color A valid R color or hex color code for the lower bound of the gradient. 
#'   Defaults to `"lightblue"`.
#' @param high_color A valid R color or hex color code for the upper bound of the gradient. 
#'   Defaults to `"navy"`.
#' @param include_zero A logical value indicating whether to include zero values for missing antecedent-consequent combinations. 
#'   Defaults to `FALSE`.
#'
#' @return A `ggplot` object representing the heatmap visualization of the association rules.
#'
#' @examples
#' library(arules)
#' data(Groceries)
#' 
#' # Generate rules
#' rules <- apriori(Groceries, parameter = list(supp = 0.01, conf = 0.5, target = "rules"))
#' 
#' # Create a heatmap of the rules using confidence as the metric
#' rule_heatmap(rules, metric = "confidence", graph_title = "Confidence Heatmap")
#' 
#' # Create a heatmap of the rules using lift as the metric
#' rule_heatmap(rules, metric = "lift", graph_title = "Lift Heatmap", low_color = "white", high_color = "red")
#'
#' @import ggplot2
#' @importFrom arules lhs rhs quality
#' @importFrom tidyr complete
#' @export

rule_heatmap <- function(rules,
                         metric = "confidence",
                         graph_title = "",
                         low_color = "lightblue",
                         high_color = "navy",
                         include_zero = FALSE) {
  
  # ensure arguments are correct types
  validate_rules_map(rules)
  validate_metric_map(metric)
  validate_title_map(graph_title)
  validate_color_map(low_color)
  validate_color_map(high_color)
  validate_logical_map(include_zero)
  
  # isolate antecedents and consequents
  antecedents <- labels(lhs(rules))
  consequents <- labels(rhs(rules))
  metric <- tolower(metric)
  
  # store in df
  rule_df <- data.frame(
    antecedents = antecedents,
    consequents = consequents,
    metric = quality(rules)[[metric]]
  )
  
  # if user wants to include 0 in the scale, allow this
  if (include_zero) {
    rule_df <- rule_df %>%
      complete(antecedents, consequents, fill = list(metric = 0))
  }
  
  colnames(rule_df) <- c("antecedents", "consequents", "metric")
  
  # generate plot
  ggplot(rule_df, aes(x = antecedents, y = consequents, fill = metric)) +
    geom_tile() +
    scale_fill_gradient(low = low_color, high = high_color) +
    labs(
      title = graph_title,
      x = "Antecedents",
      y = "Consequents",
      fill = metric
    ) +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      plot.title = element_text(hjust = 0.5),
      panel.grid = element_blank()
    )
}


#' @noRd
#' @title Validate Rules Object
#' @description Validates that the input is a non-empty `rules` object.
#' @param rules An object to check for class `rules`.
#' @return None. Throws an error if the input is not a valid `rules` object.

validate_rules_map <- function(rules) {
  if (!inherits(rules, "rules")) {
    stop("Input must be a single object of class 'rules'. Please provide a valid rule set.")
  }
  
  if (length(rules) == 0) {
    stop("`rules` object is empty. Please provide a non-empty ruleset.")
  }
}


#' @noRd
#' @title Validate Metric
#' @description Validates that the metric is one of the allowed values: `"confidence"`, `"support"`, or `"lift"`.
#' @param metric A character string specifying the metric.
#' @return None. Throws an error if the metric is invalid.

validate_metric_map <- function(metric) {
  valid_metrics <- c("confidence", "support", "lift")
  
  if (!is.character(metric) || !tolower(metric) %in% valid_metrics) {
    stop("'metric' must be one of 'confidence', 'support', or 'lift'. Please provide a valid metric.")
  }
}


#' @noRd
#' @title Validate Graph Title
#' @description Validates that the graph title is a single non-NA character string or `NULL`.
#' @param graph_title The title of the graph.
#' @return None. Throws an error if the graph title is invalid.

validate_title_map <- function(graph_title) {
  if (is.null(graph_title)) {
    return()
  }
  
  if (!is.character(graph_title) || length(graph_title) != 1 || is.na(graph_title)) {
    stop("The graph title must be either NULL or a single non-NA character string.")
  }
}


#' @noRd
#' @title Validate Color Input
#' @description Validates that the color input is a valid hex color code or an R color name.
#' @param color A color specified as a hex code or an R color name.
#' @return None. Throws an error if the color is invalid.

validate_color_map <- function(color) {
  hex_pattern <- "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{8})$"
  
  if (is.character(color) && length(color) == 1) {
    if (grepl(hex_pattern, color)) {
      return(TRUE)
    }
    if (color %in% colors()) {
      return(TRUE)
    }
  }
  
  stop(
    paste(
      "The input is not a valid hex color code or R color name.",
      "Please provide a valid hex code (e.g., '#FFFFFF')",
      "or a recognized R color name (e.g., 'red').",
      sep = " "
    )
  )
}


#' @noRd
#' @title Validate Logical Input
#' @description Validates that the input is a single logical value (`TRUE` or `FALSE`).
#' @param input The logical input to validate.
#' @return None. Throws an error if the input is not a valid logical value.

validate_logical_map <- function(input) {
  if (length(input) != 1 || !is.logical(input) || is.na(input)) {
    stop("'include_zero' must be either 'TRUE' or 'FALSE'.")
  }
}
